# Generated by Django 5.2.3 on 2025-10-28 02:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='اسم المحكمة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='ملاحظة / وصف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courts', to='accounts.department', verbose_name='الإدارة (اختياري)')),
            ],
            options={
                'verbose_name': 'محكمة',
                'verbose_name_plural': 'المحاكم',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourtDivision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم التقسيم')),
                ('note', models.TextField(blank=True, null=True, verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='courts.court', verbose_name='المحكمة')),
            ],
            options={
                'verbose_name': 'تقسيم المحكمة',
                'verbose_name_plural': 'تقسيمات المحكمة',
                'ordering': ['court__name', 'name'],
                'unique_together': {('court', 'name')},
            },
        ),
    ]
