# Generated by Django 5.2.3 on 2025-10-28 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email_alter_user_username'),
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='court',
            options={},
        ),
        migrations.AlterModelOptions(
            name='courtdivision',
            options={},
        ),
        migrations.RemoveField(
            model_name='court',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='courtdivision',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='court',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courts', to='accounts.department'),
        ),
        migrations.AlterField(
            model_name='court',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='court',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='courtdivision',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='courts.court'),
        ),
        migrations.AlterField(
            model_name='courtdivision',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='courtdivision',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
