# Generated by Django 5.2.3 on 2025-11-21 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_department_accounts_de_name_4ee611_idx_and_more"),
        ("courts", "0002_alter_court_options_alter_courtdivision_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="court",
            options={
                "ordering": ["name"],
                "verbose_name": "محكمة",
                "verbose_name_plural": "المحاكم",
            },
        ),
        migrations.AlterModelOptions(
            name="courtdivision",
            options={
                "ordering": ["court", "name"],
                "verbose_name": "قسم محكمة",
                "verbose_name_plural": "أقسام المحاكم",
            },
        ),
        migrations.AlterField(
            model_name="court",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="courts",
                to="accounts.department",
                verbose_name="الإدارة",
            ),
        ),
        migrations.AlterField(
            model_name="court",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="الوصف"),
        ),
        migrations.AlterField(
            model_name="court",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="اسم المحكمة"
            ),
        ),
        migrations.AlterField(
            model_name="courtdivision",
            name="court",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="divisions",
                to="courts.court",
                verbose_name="المحكمة",
            ),
        ),
        migrations.AlterField(
            model_name="courtdivision",
            name="name",
            field=models.CharField(max_length=255, verbose_name="اسم القسم"),
        ),
        migrations.AlterField(
            model_name="courtdivision",
            name="note",
            field=models.TextField(blank=True, null=True, verbose_name="ملاحظة"),
        ),
        migrations.AddIndex(
            model_name="court",
            index=models.Index(fields=["name"], name="courts_cour_name_39e975_idx"),
        ),
        migrations.AddIndex(
            model_name="court",
            index=models.Index(
                fields=["department"], name="courts_cour_departm_d03f89_idx"
            ),
        ),
    ]
