# Generated by Django 5.2.3 on 2025-11-24 04:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_department_accounts_de_name_4ee611_idx_and_more'),
        ('courts', '0003_alter_court_options_alter_courtdivision_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_received', models.DateField(verbose_name='تاريخ الاستلام')),
                ('general_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='الرقم العام')),
                ('case_number', models.CharField(max_length=100, verbose_name='رقم القضية')),
                ('lawsuit_number', models.CharField(max_length=100, verbose_name='رقم الدعوى')),
                ('plaintiff', models.CharField(max_length=200, verbose_name='المدعي')),
                ('defendant', models.CharField(max_length=200, verbose_name='المدعى عليه')),
                ('requests', models.TextField(verbose_name='الطلبات')),
                ('hearing_dates', models.DateField(blank=True, null=True, verbose_name='تاريخ الجلسات')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('appeal_status', models.BooleanField(blank=True, default=None, help_text='True: قيد الاستئناف, False: غير مستأنف, None: غير محدد', null=True, verbose_name='حالة الاستئناف')),
                ('case_status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('under_study', 'قيد الدراسة'), ('in_court', 'قيد التقاضي'), ('closed', 'منتهية'), ('appealed', 'قيد الاستئناف')], default='pending', max_length=20, verbose_name='حالة القضية')),
                ('file', models.FileField(blank=True, null=True, upload_to='cases/', verbose_name='الملف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('ruling', models.CharField(blank=True, choices=[('for_university', 'لصالح الجامعة'), ('against_university', 'ضد الجامعة')], max_length=20, null=True, verbose_name='الحكم الصادر')),
                ('saved_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الحفظ')),
                ('court', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='courts.court', verbose_name='المحكمة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_cases', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='accounts.department', verbose_name='الإدارة')),
                ('lawyers', models.ManyToManyField(blank=True, related_name='assigned_cases', to=settings.AUTH_USER_MODEL, verbose_name='المحامون')),
            ],
            options={
                'verbose_name': 'قضية',
                'verbose_name_plural': 'القضايا',
                'db_table': 'cases',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['general_number'], name='cases_general_22fbad_idx'), models.Index(fields=['case_number'], name='cases_case_nu_25894f_idx'), models.Index(fields=['case_status'], name='cases_case_st_d9e3c2_idx'), models.Index(fields=['date_received'], name='cases_date_re_2e7bba_idx'), models.Index(fields=['department', 'case_status'], name='cases_departm_6719eb_idx')],
            },
        ),
        migrations.CreateModel(
            name='LawyerSecretaryAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lawyer', models.ForeignKey(limit_choices_to={'role__name': 'Lawyer'}, on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_secretary_access', to=settings.AUTH_USER_MODEL, verbose_name='المحامي')),
                ('secretary', models.ForeignKey(limit_choices_to={'role__name': 'Secretary'}, on_delete=django.db.models.deletion.CASCADE, related_name='secretary_lawyer_access', to=settings.AUTH_USER_MODEL, verbose_name='السكرتيرة')),
            ],
            options={
                'verbose_name': 'صلاحية سكرتيرة لمحامي',
                'verbose_name_plural': 'صلاحيات السكرتيرات للمحامين',
                'unique_together': {('lawyer', 'secretary')},
            },
        ),
    ]
