# Generated by Django 5.2.3 on 2025-10-07 03:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_email_alter_user_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_received', models.DateField()),
                ('general_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('case_number', models.CharField(max_length=100)),
                ('lawsuit_number', models.CharField(max_length=100)),
                ('court', models.CharField(max_length=200)),
                ('plaintiff', models.CharField(max_length=200)),
                ('defendant', models.CharField(max_length=200)),
                ('requests', models.TextField()),
                ('hearing_dates', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('appeal_status', models.BooleanField(default=False)),
                ('case_status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('under_study', 'قيد الدراسة'), ('in_court', 'قيد التقاضي'), ('closed', 'منتهية'), ('appealed', 'قيد الاستئناف')], default='pending', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='cases/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_cases', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='accounts.department')),
                ('lawyers', models.ManyToManyField(blank=True, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LawyerSecretaryAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lawyer', models.ForeignKey(limit_choices_to={'role_name': 'Lawyer'}, on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_secretary_access', to=settings.AUTH_USER_MODEL, verbose_name='المحامي')),
                ('secretary', models.ForeignKey(limit_choices_to={'role_name': 'Secretary'}, on_delete=django.db.models.deletion.CASCADE, related_name='secretary_lawyer_access', to=settings.AUTH_USER_MODEL, verbose_name='السكرتيرة')),
            ],
            options={
                'verbose_name': 'صلاحية سكرتيرة لمحامي',
                'verbose_name_plural': 'صلاحيات السكرتيرات للمحامين',
                'unique_together': {('lawyer', 'secretary')},
            },
        ),
    ]
