# Generated by Django 5.2.3 on 2025-12-03 17:00

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),  # آخر مايجريشن صحيح قبل المشكلة
    ]

    operations = [
        # تعديل hearing_dates ليكون JSONField مباشرة
        migrations.AlterField(
            model_name='case',
            name='hearing_dates',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='تواريخ الجلسات'),
        ),

        # تعديل appeal_status للتأكد من null=True و default=None
        migrations.AlterField(
            model_name='case',
            name='appeal_status',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='حالة الاستئناف'),
        ),

        # تأكد من ترتيب Case حسب created_at
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-created_at']},
        ),
    ]
