# Generated by Django 5.2.3 on 2025-10-16 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyersecretaryaccess',
            name='lawyer',
            field=models.ForeignKey(limit_choices_to={'role__name': 'Lawyer'}, on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_secretary_access', to=settings.AUTH_USER_MODEL, verbose_name='المحامي'),
        ),
        migrations.AlterField(
            model_name='lawyersecretaryaccess',
            name='secretary',
            field=models.ForeignKey(limit_choices_to={'role__name': 'Secretary'}, on_delete=django.db.models.deletion.CASCADE, related_name='secretary_lawyer_access', to=settings.AUTH_USER_MODEL, verbose_name='السكرتيرة'),
        ),
    ]
