# Generated by Django 5.2.3 on 2025-12-03 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_fix_hearing_dates'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lawyersecretaryaccess',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='lawyersecretaryaccess',
            name='lawyer',
        ),
        migrations.RemoveField(
            model_name='lawyersecretaryaccess',
            name='secretary',
        ),
        migrations.RemoveIndex(
            model_name='case',
            name='cases_general_22fbad_idx',
        ),
        migrations.RemoveIndex(
            model_name='case',
            name='cases_case_nu_25894f_idx',
        ),
        migrations.RemoveIndex(
            model_name='case',
            name='cases_case_st_d9e3c2_idx',
        ),
        migrations.RemoveIndex(
            model_name='case',
            name='cases_date_re_2e7bba_idx',
        ),
        migrations.RemoveIndex(
            model_name='case',
            name='cases_departm_6719eb_idx',
        ),
        migrations.DeleteModel(
            name='LawyerSecretaryAccess',
        ),
    ]
