# Generated by Django 5.2.3 on 2025-10-28 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_alter_lawyersecretaryaccess_lawyer_and_more'),
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='courts.court'),
        ),
    ]
