# Generated by Django 5.2.3 on 2025-11-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_case_court'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='appeal_status',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
