# Generated by Django 5.2.3 on 2025-12-03 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_lawyersecretaryaccess_unique_together_and_more'),
        ('cases', '0004_fix_hearing_dates_json'),
    ]

    operations = [
    ]
