# Generated by Django 5.2.3 on 2025-11-21 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_department_accounts_de_name_4ee611_idx_and_more"),
        ("cases", "0004_alter_case_appeal_status"),
        ("courts", "0003_alter_court_options_alter_courtdivision_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="case",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "قضية",
                "verbose_name_plural": "القضايا",
            },
        ),
        migrations.AlterField(
            model_name="case",
            name="appeal_status",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="True: قيد الاستئناف, False: غير مستأنف, None: غير محدد",
                null=True,
                verbose_name="حالة الاستئناف",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="case_number",
            field=models.CharField(max_length=100, verbose_name="رقم القضية"),
        ),
        migrations.AlterField(
            model_name="case",
            name="case_status",
            field=models.CharField(
                choices=[
                    ("pending", "قيد الانتظار"),
                    ("under_study", "قيد الدراسة"),
                    ("in_court", "قيد التقاضي"),
                    ("closed", "منتهية"),
                    ("appealed", "قيد الاستئناف"),
                ],
                default="pending",
                max_length=20,
                verbose_name="حالة القضية",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="court",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cases",
                to="courts.court",
                verbose_name="المحكمة",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="case",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_cases",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشئ بواسطة",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="date_received",
            field=models.DateField(verbose_name="تاريخ الاستلام"),
        ),
        migrations.AlterField(
            model_name="case",
            name="defendant",
            field=models.CharField(max_length=200, verbose_name="المدعى عليه"),
        ),
        migrations.AlterField(
            model_name="case",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cases",
                to="accounts.department",
                verbose_name="الإدارة",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="cases/", verbose_name="الملف"
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="general_number",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="الرقم العام",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="hearing_dates",
            field=models.DateField(blank=True, null=True, verbose_name="تاريخ الجلسات"),
        ),
        migrations.AlterField(
            model_name="case",
            name="lawsuit_number",
            field=models.CharField(max_length=100, verbose_name="رقم الدعوى"),
        ),
        migrations.AlterField(
            model_name="case",
            name="lawyers",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_cases",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المحامون",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="notes",
            field=models.TextField(blank=True, default="", verbose_name="ملاحظات"),
        ),
        migrations.AlterField(
            model_name="case",
            name="plaintiff",
            field=models.CharField(max_length=200, verbose_name="المدعي"),
        ),
        migrations.AlterField(
            model_name="case",
            name="requests",
            field=models.TextField(verbose_name="الطلبات"),
        ),
        migrations.AlterField(
            model_name="case",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(
                fields=["general_number"], name="cases_general_22fbad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(fields=["case_number"], name="cases_case_nu_25894f_idx"),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(fields=["case_status"], name="cases_case_st_d9e3c2_idx"),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(
                fields=["date_received"], name="cases_date_re_2e7bba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(
                fields=["department", "case_status"], name="cases_departm_6719eb_idx"
            ),
        ),
    ]
