# Generated by Django 5.2.3 on 2025-12-21 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_merge_20251203_1821'),
        ('courts', '0003_alter_court_options_alter_courtdivision_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='courts.courtdivision'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_number',
            field=models.CharField(max_length=100, verbose_name='رقم الحصر'),
        ),
        migrations.AlterField(
            model_name='case',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courts.court'),
        ),
        migrations.AlterField(
            model_name='case',
            name='defendant',
            field=models.CharField(max_length=200, verbose_name='اسم المدعى عليه'),
        ),
        migrations.AlterField(
            model_name='case',
            name='plaintiff',
            field=models.CharField(max_length=200, verbose_name='اسم المدعي'),
        ),
    ]
