# Generated by Django 5.2.3 on 2025-12-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0005_merge_20251203_1821"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="case_number",
            field=models.CharField(max_length=100, verbose_name="رقم الحصر"),
        ),
        migrations.AlterField(
            model_name="case",
            name="defendant",
            field=models.CharField(max_length=200, verbose_name="اسم المدعى عليه"),
        ),
        migrations.AlterField(
            model_name="case",
            name="plaintiff",
            field=models.CharField(max_length=200, verbose_name="اسم المدعي"),
        ),
    ]
