# Generated by Django 5.2.3 on 2025-12-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0006_alter_case_case_number_alter_case_defendant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="hearing_dates",
            field=models.JSONField(
                blank=True, default=list, verbose_name="تواريخ الجلسات"
            ),
        ),
    ]
