# Generated by Django 5.2.3 on 2025-12-22 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_case_division_alter_case_case_number_and_more'),
        ('cases', '0007_alter_case_hearing_dates'),
    ]

    operations = [
    ]
