# Generated by Django 5.2.3 on 2025-10-04 12:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_email_alter_user_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_received', models.DateField(verbose_name='تاريخ ورود العقد')),
                ('general_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الحصر العام')),
                ('contract_number', models.CharField(max_length=50, verbose_name='رقم حصر العقود')),
                ('contract_type', models.CharField(choices=[('tender', 'مناقصة'), ('practice', 'ممارسة'), ('direct', 'أمر مباشر'), ('protocol', 'بروتوكول إسناد')], max_length=50, verbose_name='نوع العقد')),
                ('content', models.TextField(verbose_name='مضمون العقد')),
                ('progress', models.TextField(verbose_name='ما تم في العقد')),
                ('archive_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الحفظ')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('file', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='ملف العقد')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='accounts.department', verbose_name='الإدارة')),
            ],
            options={
                'verbose_name': 'عقد',
                'verbose_name_plural': 'العقود',
                'ordering': ['-date_received', '-id'],
            },
        ),
    ]
