# Generated by Django 5.2.3 on 2025-10-08 09:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_email_alter_user_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('general_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='الرقم العام')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان التحقيق')),
                ('description', models.TextField(verbose_name='وصف التحقيق')),
                ('accused_names', models.TextField(help_text='يمكن إدخال أسماء متعددة مفصولة بفاصلة', verbose_name='أسماء المتهمين')),
                ('date_received', models.DateField(verbose_name='تاريخ الاستلام')),
                ('date_started', models.DateField(blank=True, null=True, verbose_name='تاريخ بداية التحقيق')),
                ('date_completed', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء التحقيق')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('under_investigation', 'قيد التحقيق'), ('completed', 'مكتمل'), ('closed', 'مغلق'), ('appealed', 'قيد الاستئناف')], default='pending', max_length=20, verbose_name='حالة التحقيق')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='medium', max_length=10, verbose_name='الأولوية')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('findings', models.TextField(blank=True, default='', verbose_name='النتائج')),
                ('recommendations', models.TextField(blank=True, default='', verbose_name='التوصيات')),
                ('file', models.FileField(blank=True, null=True, upload_to='investigations/', verbose_name='الملف المرفق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('assigned_investigators', models.ManyToManyField(blank=True, related_name='assigned_investigations', to=settings.AUTH_USER_MODEL, verbose_name='المحققون المعينون')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_investigations', to=settings.AUTH_USER_MODEL, verbose_name='منشئ التحقيق')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='accounts.department', verbose_name='الإدارة')),
            ],
            options={
                'verbose_name': 'تحقيق',
                'verbose_name_plural': 'التحقيقات',
                'db_table': 'investigations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appeal_number', models.CharField(max_length=100, unique=True, verbose_name='رقم الاستئناف')),
                ('appellant_name', models.CharField(max_length=200, verbose_name='اسم المستأنف')),
                ('appeal_reason', models.TextField(verbose_name='سبب الاستئناف')),
                ('date_submitted', models.DateField(verbose_name='تاريخ تقديم الاستئناف')),
                ('date_reviewed', models.DateField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('status', models.CharField(choices=[('submitted', 'مقدم'), ('under_review', 'قيد المراجعة'), ('accepted', 'مقبول'), ('rejected', 'مرفوض'), ('withdrawn', 'منسحب')], default='submitted', max_length=20, verbose_name='حالة الاستئناف')),
                ('decision', models.TextField(blank=True, default='', verbose_name='القرار')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('file', models.FileField(blank=True, null=True, upload_to='appeals/', verbose_name='ملف الاستئناف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_appeals', to=settings.AUTH_USER_MODEL, verbose_name='منشئ الاستئناف')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_appeals', to=settings.AUTH_USER_MODEL, verbose_name='مراجع الاستئناف')),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='investigations.investigation', verbose_name='التحقيق')),
            ],
            options={
                'verbose_name': 'استئناف',
                'verbose_name_plural': 'الاستئنافات',
                'db_table': 'appeals',
                'ordering': ['-created_at'],
            },
        ),
    ]
