# Generated by Django 5.2.3 on 2025-10-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigation',
            name='case_type',
            field=models.CharField(choices=[('against_university', 'ضد الجامعة'), ('by_university', 'مرفوعة من الجامعة'), ('internal_disciplinary', 'تأديبية داخلية'), ('academic_misconduct', 'مخالفة أكاديمية'), ('administrative', 'إدارية')], default='internal_disciplinary', max_length=30, verbose_name='نوع القضية'),
        ),
        migrations.AddField(
            model_name='investigation',
            name='complainant_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم هوية/كود المشتكي'),
        ),
        migrations.AddField(
            model_name='investigation',
            name='complainant_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم المشتكي'),
        ),
        migrations.AddField(
            model_name='investigation',
            name='complainant_type',
            field=models.CharField(blank=True, choices=[('student', 'طالب'), ('faculty_member', 'عضو هيئة تدريس'), ('employee', 'موظف'), ('external_party', 'طرف خارجي'), ('university', 'الجامعة')], max_length=20, null=True, verbose_name='نوع المشتكي'),
        ),
        migrations.AddField(
            model_name='investigation',
            name='faculty_college',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الكلية المعنية'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('under_investigation', 'قيد التحقيق'), ('completed', 'مكتمل'), ('closed', 'مغلق'), ('appealed', 'قيد الاستئناف'), ('referred_to_court', 'محال للقضاء'), ('settled', 'تم التسوية')], default='pending', max_length=20, verbose_name='حالة التحقيق'),
        ),
    ]
