# Generated by Django 5.2.3 on 2025-10-16 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0002_investigation_case_type_investigation_complainant_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='complainant',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
