# Generated by Django 5.2.3 on 2025-10-17 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email_alter_user_username'),
        ('investigations', '0003_appeal_complainant'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='accounts.department', verbose_name='الإدارة'),
        ),
    ]
