# Generated by Django 5.2.3 on 2025-10-28 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0004_appeal_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='appeal_number',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='رقم الاستئناف'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='complainant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to=settings.AUTH_USER_MODEL, verbose_name='المشتكي'),
        ),
    ]
