# Generated by Django 5.2.3 on 2025-11-21 23:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_department_accounts_de_name_4ee611_idx_and_more"),
        ("investigations", "0005_alter_appeal_appeal_number_alter_appeal_complainant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="appeal",
            index=models.Index(
                fields=["appeal_number"], name="appeals_appeal__984076_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appeal",
            index=models.Index(fields=["status"], name="appeals_status_79945f_idx"),
        ),
        migrations.AddIndex(
            model_name="appeal",
            index=models.Index(
                fields=["date_submitted"], name="appeals_date_su_44453e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appeal",
            index=models.Index(
                fields=["investigation", "status"], name="appeals_investi_348957_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investigation",
            index=models.Index(
                fields=["general_number"], name="investigati_general_0ce0a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investigation",
            index=models.Index(fields=["status"], name="investigati_status_295316_idx"),
        ),
        migrations.AddIndex(
            model_name="investigation",
            index=models.Index(
                fields=["priority"], name="investigati_priorit_0407e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investigation",
            index=models.Index(
                fields=["date_received"], name="investigati_date_re_cf524b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investigation",
            index=models.Index(
                fields=["department", "status"], name="investigati_departm_51ba4e_idx"
            ),
        ),
    ]
