# Generated by Django 5.2.3 on 2025-11-21 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_email_alter_user_username"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["name"], name="accounts_de_name_4ee611_idx"),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["code"], name="accounts_de_code_b809b1_idx"),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["name"], name="accounts_ro_name_183ba5_idx"),
        ),
    ]
