# Generated by Django 5.2.3 on 2025-12-22 10:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0005_alter_user_managers_user_deactivated_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Fatwa",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "general_number",
                    models.BigIntegerField(
                        blank=True, null=True, unique=True, verbose_name="الرقم العام"
                    ),
                ),
                ("request_content", models.TextField(verbose_name="محتوى الطلب")),
                (
                    "result",
                    models.TextField(blank=True, null=True, verbose_name="النتيجة"),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="fatwas/", verbose_name="الملف"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.department",
                        verbose_name="الإدارة",
                    ),
                ),
            ],
            options={
                "verbose_name": "فتوى",
                "verbose_name_plural": "الفتاوى",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["general_number"], name="fatwas_fatw_general_76b263_idx"
                    ),
                    models.Index(
                        fields=["department"], name="fatwas_fatw_departm_0ab81e_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="fatwas_fatw_created_0cc5e7_idx"
                    ),
                ],
            },
        ),
    ]
