# Generated by Django 5.2.3 on 2025-12-03 17:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_department_accounts_de_name_4ee611_idx_and_more'),
        ('fatwas', '0004_alter_fatwa_general_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fatwa',
            options={'ordering': ['-created_at'], 'verbose_name': 'فتوى', 'verbose_name_plural': 'الفتاوى'},
        ),
        migrations.AlterField(
            model_name='fatwa',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='fatwa',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='fatwa',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='fatwas/', verbose_name='الملف'),
        ),
        migrations.AlterField(
            model_name='fatwa',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fatwa',
            name='request_content',
            field=models.TextField(verbose_name='محتوى الطلب'),
        ),
        migrations.AlterField(
            model_name='fatwa',
            name='result',
            field=models.TextField(blank=True, null=True, verbose_name='النتيجة'),
        ),
        migrations.AddIndex(
            model_name='fatwa',
            index=models.Index(fields=['general_number'], name='fatwas_fatw_general_76b263_idx'),
        ),
        migrations.AddIndex(
            model_name='fatwa',
            index=models.Index(fields=['department'], name='fatwas_fatw_departm_0ab81e_idx'),
        ),
        migrations.AddIndex(
            model_name='fatwa',
            index=models.Index(fields=['created_at'], name='fatwas_fatw_created_0cc5e7_idx'),
        ),
    ]
