# Generated by Django 5.2.3 on 2025-12-03 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fatwas', '0005_alter_fatwa_options_alter_fatwa_created_at_and_more'),
        ('fatwas', '0006_convert_general_number_to_char'),
    ]

    operations = [
    ]
